### ISSUE TITLE
Two SessionBuddy menus after an update

### ISSUE THREAD

**Issue by grahamperrin** [Ulf3000/sessionBuddy#2]
I guess, the workaround will be to quit: 

![2018-10-29 06 00 24 update capabilities issue -1 ulf3000-sessionbuddy](https://user-images.githubusercontent.com/192271/47632090-82951b80-db40-11e8-9ae1-4e6ff17babea.png)

![2018-10-29 06 00 49 update capabilities issue -1 ulf3000-sessionbuddy](https://user-images.githubusercontent.com/192271/47632098-8759cf80-db40-11e8-9ba9-e379f44c742f.png)

**Comment by grahamperrin** [comment]
OK, now I see (paying closer attention): 

> it doesnt have any removal functions(cause im too lazy) so if you wanna deinstall it you have to either restart the browser or just wait till you restart anyways ... 

`:-)` that's at https://redd.it/9oygw7 (and fair enough for a bare-bones extension (and hey you're **far** from lazy!)) however there's no comparable hint at https://github.com/Ulf3000/sessionBuddy/blob/master/README.md

I guess, leave this issue open for pull requests for: 

1. documentation
2. possible addition of removal functions. 

----

I might tackle (1). You might have seen some accidental PRs from me (oops!) but I'm just about capable of an intentional, methodical PR e.g. `https://github.com/JustOff/ca-archive/pull/17/commits`

**Comment by Ulf3000** [comment]
thanx i added that to the readme ! 

i dont wanna put to much energy in making these addons completely compatible with the addon system as i dont even know if bootstrapped loading will exist for how long .. maybe i need to convert that stuff into a config.js loader someday anyways and then theres no unloader anymore anyways

**Comment by Ulf3000** [comment]
fixed .. can be closed

**Comment by Ulf3000** [comment]
alternatively i can also just make a customizable ui item , which can be dragged around like a button
